# Gitleaks configuration for MFR project
# This configuration allows only specific user information and blocks all other secrets

title = "MFR Gitleaks Config"

# Extend the base configuration
[extend]
useDefault = true

# Define allowed patterns that should NOT be flagged as secrets
[allowlist]
description = "Global allowlist"
paths = [
    '''\.gitleaks\.toml$''',
    '''\.env\.example$''',
    '''\.env\.template$''',
]
regexes = [
    '''Emasoft''',
    '''713559\+Emasoft@users\.noreply\.github\.com''',
    '''GIT_AUTHOR=Emasoft''',
    '''GIT_AUTHOR_EMAIL=713559\+Emasoft@users\.noreply\.github\.com''',
    '''GIT_COMMITTER=Emasoft''',
    '''GIT_COMMITTER_EMAIL=713559\+Emasoft@users\.noreply\.github\.com''',
    '''user\.name\s*=\s*"?Emasoft"?''',
    '''user\.email\s*=\s*"?713559\+Emasoft@users\.noreply\.github\.com"?''',
    '''<your-.*-here>''',
    '''your-.*-key''',
    '''example-.*''',
    '''placeholder.*''',
    '''https?://localhost(:[0-9]+)?''',
    '''https?://127\.0\.0\.1(:[0-9]+)?''',
    '''https?://0\.0\.0\.0(:[0-9]+)?''',
    '''https?://\[::1\](:[0-9]+)?''',
]

# Custom rules to catch common secret patterns
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_\-\s]?key|apikey)[_\-\s]?[:=]\s*['\"]?[a-zA-Z0-9]{16,}['\"]?'''
tags = ["key", "API", "generic"]

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)(secret|password|passwd|pwd)[_\-\s]?[:=]\s*['\"]?[a-zA-Z0-9]{8,}['\"]?'''
tags = ["secret", "generic"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]
