extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: false  # Allow GitHub Actions style where lists align with parent
  document-start:
    present: false

ignore: |-
  .venv/
  venv/
  .git/
  dist/
  build/
  .mypy_cache/
  .pytest_cache/
  uv.lock
  .pre-commit-config.yaml
