name: Sequential PR Auto-Fix

on:
  pull_request:
    types: [opened, synchronize]

# Prevent concurrent PR fixes
concurrency:
  group: prfix-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

env:
  PRE_COMMIT_MAX_WORKERS: 1
  CI_SEQUENTIAL_MODE: 1

jobs:
  sequential-autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Setup environment
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --all-extras
        uv pip install pre-commit

    - name: Run sequential fixes
      id: autofix
      run: |
        source .venv/bin/activate
        source .sequential-precommit-env || true

        # Track if changes were made
        git diff --exit-code && NO_CHANGES=true || NO_CHANGES=false

        # Run auto-fixable hooks only
        pre-commit run --all-files || true

        # Check if fixes were applied
        git diff --exit-code && FIXES_APPLIED=false || FIXES_APPLIED=true

        echo "fixes_applied=$FIXES_APPLIED" >> $GITHUB_OUTPUT

    - name: Commit fixes
      if: steps.autofix.outputs.fixes_applied == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "fix: Auto-fix formatting and linting issues (sequential)"
        git push

    - name: Comment on PR
      if: steps.autofix.outputs.fixes_applied == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Sequential auto-fixes applied! Please pull the latest changes.'
          })
