name: PR Auto-Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.7.13"

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    name: Auto-fix PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --frozen --all-extras

    - name: Run ruff format
      run: |
        uv run ruff format --line-length=400 --isolated src/ tests/

    - name: Run ruff check with fixes
      run: |
        uv run ruff check --ignore E203,E402,E501,E266,W505,F841,F842,F401,W293,I001,UP015,C901,W291 \
          --isolated --fix --output-format full src/ tests/ || true

    - name: Format YAML files in .github
      run: |
        if command -v yamlfmt &> /dev/null || [ -f "$HOME/go/bin/yamlfmt" ]; then
          yamlfmt -path .github/workflows || "$HOME/go/bin/yamlfmt" -path .github/workflows || true
        fi

    - name: Check for changes
      id: check-changes
      run: |
        git config --local user.email "713559+Emasoft@users.noreply.github.com"
        git config --local user.name "Emasoft"
        git add -A
        if git diff --staged --quiet; then
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        else
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |-
        git commit -m "style: auto-fix formatting issues

        Applied automatic formatting fixes:
        - Python formatting with ruff (line length 400)
        - Python linting fixes with ruff
        - YAML formatting for GitHub workflows"
        git push
