name: Security Scan

on:
  schedule:
  # Run daily at 2 AM UTC
  - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual runs

# Only allow one security scan at a time, but don't cancel in progress
concurrency:
  group: ${{ github.workflow }}-security-scan
  cancel-in-progress: false

jobs:
  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for scanning

    - name: Run TruffleHog v3
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        # For scheduled runs, scan entire repository
        extra_args: >-
          --no-verification
          --exclude-detectors generic-api-key,email

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.13"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock

    - name: Set up Python
      run: |
        uv python install 3.11
        uv python pin 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run pip-audit
      run: |
        uv pip install pip-audit
        uv run pip-audit
      continue-on-error: true

    - name: Run safety check
      run: |
        uv pip install safety
        uv run safety check --json
      continue-on-error: true
