name: Security Scan

on:
  schedule:
  # Run daily at 2 AM UTC
  - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual runs

# Only allow one security scan at a time, but don't cancel in progress
concurrency:
  group: ${{ github.workflow }}-security-scan
  cancel-in-progress: false

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_CONFIG: .gitleaks.toml

    - name: Upload Gitleaks Report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: |
          gitleaks-report.json
          gitleaks-report.sarif
        retention-days: 30

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.13"
        enable-cache: true
        cache-dependency-glob: |
          pyproject.toml
          uv.lock

    - name: Set up Python
      run: |
        uv python install 3.11
        uv python pin 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run pip-audit
      run: |
        uv pip install pip-audit
        uv run pip-audit
      continue-on-error: true

    - name: Run safety check
      run: |
        uv pip install safety
        uv run safety check --json
      continue-on-error: true
